//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reload.Platform.Graphics.OpenGl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reload.Platform.Graphics.OpenGl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics backend is not supported..
        /// </summary>
        internal static string BackendNotSupportedError {
            get {
                return ResourceManager.GetString("BackendNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |{0}| {1}/{2}: {3}..
        /// </summary>
        internal static string GraphicsManager_OnDebug {
            get {
                return ResourceManager.GetString("GraphicsManager_OnDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenGL native api binding is null..
        /// </summary>
        internal static string OpenGlApiIsNull {
            get {
                return ResourceManager.GetString("OpenGlApiIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add attribute. Linking already complete..
        /// </summary>
        internal static string ShaderCantAddAttribute {
            get {
                return ResourceManager.GetString("ShaderCantAddAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t compile shader. Linking already complete..
        /// </summary>
        internal static string ShaderCantCompile {
            get {
                return ResourceManager.GetString("ShaderCantCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t link shaders. Linking already complete..
        /// </summary>
        internal static string ShaderCantLink {
            get {
                return ResourceManager.GetString("ShaderCantLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader dictionary is null or empty..
        /// </summary>
        internal static string ShaderDictionaryNullOrEmpty {
            get {
                return ResourceManager.GetString("ShaderDictionaryNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknownshader data type..
        /// </summary>
        internal static string UnknownShaderDataType {
            get {
                return ResourceManager.GetString("UnknownShaderDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex buffer has no layout..
        /// </summary>
        internal static string VertexBufferHasNoLayout {
            get {
                return ResourceManager.GetString("VertexBufferHasNoLayout", resourceCulture);
            }
        }
    }
}
