// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("DocumentationHeader", "ClassDocumentationHeader:The class must have a documentation header.", Justification = "<Pending>", Scope = "type", Target = "~T:Reload.Core.Math3D.Tests.Vertices.VertexTests.DataHelper")]
[assembly: SuppressMessage("DocumentationHeader", "ClassDocumentationHeader:The class must have a documentation header.", Justification = "<Pending>", Scope = "type", Target = "~T:Reload.Core.Math3D.Tests.Vertices.VertexTests.VertexTests")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Vertices.VertexTests.VertexTests.Vertex_EqualsOverrideTests")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Vertices.VertexTests.DataHelper.CreateWithDefaultValues~Reload.Core.Math3D.Vertices.Vertex")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Vertices.VertexTests.DataHelper.CreateWithDifferentValues~Reload.Core.Math3D.Vertices.Vertex")]
[assembly: SuppressMessage("DocumentationHeader", "ClassDocumentationHeader:The class must have a documentation header.", Justification = "<Pending>", Scope = "type", Target = "~T:Reload.Core.Math3D.Tests.Vertices.AnimatedVertexTests.DataHelper")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Vertices.AnimatedVertexTests.DataHelper.CreateWithDefaultValues~Reload.Core.Math3D.Vertices.AnimatedVertex")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Vertices.AnimatedVertexTests.DataHelper.CreateWithDifferentValues~Reload.Core.Math3D.Vertices.AnimatedVertex")]
[assembly: SuppressMessage("DocumentationHeader", "ClassDocumentationHeader:The class must have a documentation header.", Justification = "<Pending>", Scope = "type", Target = "~T:Reload.Core.Math3D.Tests.Vertices.AnimatedVertexTests.AnimatedVertexTests")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Vertices.AnimatedVertexTests.AnimatedVertexTests.AnimatedVertex_EqualsOverrideTests")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Vertices.AnimatedVertexTests.AnimatedVertexTests.AnimatedVertex_AddBoneData_ShouldNotThrowExceptionIfExeedingDataSize")]
[assembly: SuppressMessage("DocumentationHeader", "ClassDocumentationHeader:The class must have a documentation header.", Justification = "<Pending>", Scope = "type", Target = "~T:Reload.Core.Math3D.Tests.Vertices.IndexTests.IndexTests")]
[assembly: SuppressMessage("DocumentationHeader", "ClassDocumentationHeader:The class must have a documentation header.", Justification = "<Pending>", Scope = "type", Target = "~T:Reload.Core.Math3D.Tests.Vertices.IndexTests.DataHelper")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Vertices.IndexTests.DataHelper.CreateWithDefaultValues~Reload.Core.Math3D.Vertices.Index")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Vertices.IndexTests.DataHelper.CreateWithDifferentValues~Reload.Core.Math3D.Vertices.Index")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Vertices.IndexTests.IndexTests.Index_EqualsOverrideTests")]
[assembly: SuppressMessage("DocumentationHeader", "ClassDocumentationHeader:The class must have a documentation header.", Justification = "<Pending>", Scope = "type", Target = "~T:Reload.Core.Math3D.Tests.Primitives.TriangleTests.DataHelper")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Primitives.TriangleTests.DataHelper.CreateWithDefaultValues~Reload.Core.Math3D.Primitives.Triangle")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Primitives.TriangleTests.DataHelper.CreateWithDifferentValues~Reload.Core.Math3D.Primitives.Triangle")]
[assembly: SuppressMessage("DocumentationHeader", "ClassDocumentationHeader:The class must have a documentation header.", Justification = "<Pending>", Scope = "type", Target = "~T:Reload.Core.Math3D.Tests.Primitives.TriangleTests.TriangleTests")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Primitives.TriangleTests.TriangleTests.Triangle_EqualsOverrideTests")]
[assembly: SuppressMessage("DocumentationHeader", "ClassDocumentationHeader:The class must have a documentation header.", Justification = "<Pending>", Scope = "type", Target = "~T:Reload.Core.Math3D.Tests.Vertices.BoneInfoTests.BoneInfoTests")]
[assembly: SuppressMessage("DocumentationHeader", "ClassDocumentationHeader:The class must have a documentation header.", Justification = "<Pending>", Scope = "type", Target = "~T:Reload.Core.Math3D.Tests.Vertices.BoneInfoTests.DataHelper")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Vertices.BoneInfoTests.DataHelper.CreateWithDefaultValues~Reload.Core.Math3D.Vertices.BoneInfo")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Vertices.BoneInfoTests.DataHelper.CreateWithDifferentValues~Reload.Core.Math3D.Vertices.BoneInfo")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:Reload.Core.Math3D.Tests.Vertices.BoneInfoTests.BoneInfoTests.BoneInfo_EqualsOverrideTests")]
