//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reload.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reload.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument of type BufferElement is null.
        /// </summary>
        internal static string BufferElementNullArgumentMessage {
            get {
                return ResourceManager.GetString("BufferElementNullArgumentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to build the game system....
        /// </summary>
        internal static string BuildStartingMessage {
            get {
                return ResourceManager.GetString("BuildStartingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null reference is passed to a method that does not accept it as a valid argument.
        /// </summary>
        internal static string DefaultNullArgumentMessage {
            get {
                return ResourceManager.GetString("DefaultNullArgumentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Parameter} platform is not supported..
        /// </summary>
        internal static string DefaultOSPlatfromNotSupportedMessage {
            get {
                return ResourceManager.GetString("DefaultOSPlatfromNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid shader data type..
        /// </summary>
        internal static string InvalidShaderDataType {
            get {
                return ResourceManager.GetString("InvalidShaderDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null reference is passed to a method that does not accept it as a valid argument. Parameter: {ParamName}.
        /// </summary>
        internal static string NullArgumentMessage {
            get {
                return ResourceManager.GetString("NullArgumentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex has more than four bones/weights affecting it, extra data will be discarded (BoneID={0}, Weight={1}).
        /// </summary>
        internal static string VertexHasMoreThanFourBones {
            get {
                return ResourceManager.GetString("VertexHasMoreThanFourBones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With audio backend: {AudioBackend}.
        /// </summary>
        internal static string WithAudioBackendMessage {
            get {
                return ResourceManager.GetString("WithAudioBackendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With graphics backend: {GraphicsBackend}.
        /// </summary>
        internal static string WithGraphicsBackendMessage {
            get {
                return ResourceManager.GetString("WithGraphicsBackendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With window: {WindowPlatform}.
        /// </summary>
        internal static string WithWindowMessage {
            get {
                return ResourceManager.GetString("WithWindowMessage", resourceCulture);
            }
        }
    }
}
